apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: postgres-vdb-environment-delete
  title: Delete PostgreSQL VDB Environment
  description: Safely delete a PostgreSQL Virtual Database environment with automatic cleanup and Git synchronization
  tags:
    - postgres
    - database
    - gitops
    - delphix
    - vdb
    - delete
spec:
  owner: user:default/dcstolf
  type: resource
  
  parameters:
    - title: Environment to Delete
      required:
        - environmentName
        - confirmDeletion
      properties:
        environmentName:
          title: Environment Name
          type: string
          description: Select the environment to delete from the list of active ArgoCD applications
          ui:field: SelectFieldFromApi
          ui:options:
            title: Select Environment
            description: Choose from currently deployed environments
            path: 'proxy/argocd/api/v1/applicationsets/postgres-vdb-appset'
            arraySelector: 'status.resources'
            valueSelector: 'metadata.labels.environment'
            labelSelector: 'metadata.labels.environment'
        
        confirmDeletion:
          title: Confirm Deletion
          type: boolean
          description: I understand this action will permanently delete the environment and all its data
          default: false
          ui:widget: checkbox
          ui:help: 'This action cannot be undone. All VDB data will be lost.'
        
        reason:
          title: Deletion Reason
          type: string
          description: Why is this environment being deleted? (for audit purposes)
          ui:widget: textarea
          ui:options:
            rows: 3
  
  steps:
    - id: validate-confirmation
      name: Validate Deletion Confirmation
      action: debug:log
      input:
        message: |
          Validating deletion request for environment: ${{ parameters.environmentName }}
          Confirmation: ${{ parameters.confirmDeletion }}
    
    - id: check-confirmation
      name: Check Confirmation
      if: ${{ parameters.confirmDeletion === false }}
      action: catalog:fail
      input:
        message: 'Deletion cancelled: confirmation checkbox was not checked'
    
    - id: fetch-repo
      name: Fetch Repository
      action: fetch:plain
      input:
        url: https://github.com/DCSTOLF/postgresvdb-environments
        targetPath: ./repo
    
    - id: delete-environment
      name: Delete Environment Directory
      action: fs:delete
      input:
        files:
          - ./repo/environments/${{ parameters.environmentName }}
    
    - id: create-pr
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=postgresvdb-environments&owner=DCSTOLF
        branchName: delete-environment-${{ parameters.environmentName }}
        title: 'Delete PostgreSQL VDB environment: ${{ parameters.environmentName }}'
        description: |
          ## Environment Deletion
          
          **Environment**: `${{ parameters.environmentName }}`
          **Reason**: ${{ parameters.reason }}
          **Deleted by**: ${{ user.entity.metadata.name }}
          **Timestamp**: ${{ '' | now }}
          
          ### What happens after merge:
          
          1. **ArgoCD ApplicationSet** will detect the directory removal within 3-10 seconds
          2. **Application CR** will be pruned automatically
          3. **Cascade deletion** will clean up all resources:
             - PostgresVDB custom resource
             - Secrets
             - ConfigMaps
             - Services
             - All other Helm-managed resources
          4. **Namespace** will be cleaned up (may require manual deletion - ArgoCD limitation)
          
          ### Manual verification after merge:
          
          ```bash
          # Wait ~30 seconds after merge, then verify:
          kubectl get application postgres-vdb-${{ parameters.environmentName }} -n argocd  # Should be NotFound
          kubectl get postgresvdb -n postgres-vdbs-${{ parameters.environmentName }}        # Should be NotFound
          kubectl get namespace postgres-vdbs-${{ parameters.environmentName }}             # May still exist
          ```
          
          ---
          *Created via Backstage Software Template*
          
          **⚠️  Review carefully before merging** - This will trigger automatic deletion of all environment resources.
        sourcePath: ./repo
  
  output:
    links:
      - title: Pull Request
        url: ${{ steps['create-pr'].output.remoteUrl }}
        icon: github
    text:
      - title: Summary
        content: |
          ## Deletion Initiated
          
          A pull request has been created to remove the **${{ parameters.environmentName }}** environment from Git.
          
          ### PR Details:
          - **URL**: ${{ steps['create-pr'].output.remoteUrl }}
          - **Branch**: `delete-environment-${{ parameters.environmentName }}`
          
          ### What happens next:
          
          1. **Review the PR** to confirm the environment should be deleted
          2. **Merge the PR** when ready
          3. **ArgoCD will automatically**:
             - Detect the directory removal (within 3-10 seconds)
             - Prune the Application CR
             - Trigger cascade deletion of all resources
          
          ### Verification (after merge):
          
          Wait ~30 seconds after merging, then run:
          ```bash
          # Check Application (should be gone)
          kubectl get application postgres-vdb-${{ parameters.environmentName }} -n argocd
          
          # Check VDB (should be gone)
          kubectl get postgresvdb -n postgres-vdbs-${{ parameters.environmentName }}
          
          # Check namespace (may need manual cleanup)
          kubectl get namespace postgres-vdbs-${{ parameters.environmentName }}
          ```
          
          ### If namespace remains:
          ```bash
          kubectl delete namespace postgres-vdbs-${{ parameters.environmentName }}
          ```
